package parammatrix.model;

public enum ReflectionContext {
    HTML_TEXT,
    HTML_ATTRIBUTE_SINGLE_QUOTED,
    HTML_ATTRIBUTE_DOUBLE_QUOTED,
    HTML_ATTRIBUTE_UNQUOTED,
    SCRIPT_BLOCK,
    JAVASCRIPT_SINGLE_QUOTED_STRING,
    JAVASCRIPT_DOUBLE_QUOTED_STRING,
    JAVASCRIPT_TEMPLATE_LITERAL,
    COMMENT,
    URL_ATTRIBUTE,
    CSS,
    UNKNOWN
}

